<#
.SYNOPSIS
Build the single-file audit script from the module sources.

.DESCRIPTION
Most people who want this audit want one thing: a report. Installing a module, trusting the Gallery
and carrying a dependency is a lot of ceremony for a file you run once a quarter. So the report path
also ships as one script you download and run.

The script is generated, never maintained by hand. It inlines the catalog, the report template and
every function the read path needs, in dependency order, and ends with a small main body that
connects, collects and writes the report. Whatever is fixed in the module is fixed here on the next
build, which is the whole reason the module exists.

The write path is deliberately not in the script. Removing an assignment is what the module is for,
where the input is typed, every call is confirmed and everything is backed up first.

.PARAMETER Check
Build into memory and compare against the committed file. Exits non-zero on a difference.

.EXAMPLE
./tools/Build-StandaloneScript.ps1

.EXAMPLE
./tools/Build-StandaloneScript.ps1 -Check
#>
[CmdletBinding()]
param(
    [Parameter()]
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Path $PSScriptRoot -Parent
$moduleRoot = Join-Path $repoRoot 'src' 'RiskyRolesAnalyzer'
$outputPath = Join-Path $repoRoot 'dist' 'Invoke-RiskyRolesAudit.ps1'
$manifest = Test-ModuleManifest -Path (Join-Path $moduleRoot 'RiskyRolesAnalyzer.psd1')
$version = "$($manifest.Version)$(if ($manifest.PrivateData.PSData.Prerelease) { "-$($manifest.PrivateData.PSData.Prerelease)" })"

# Only what the read path needs. Remove, Restore and Show stay in the module on purpose.
$publicNeeded = @('Connect-RiskyRolesAnalyzer', 'Get-RiskyRoleAssignment', 'Export-RiskyRoleReport')

function Get-FunctionBody {
    # The file without its trailing newline noise; each file holds exactly one function.
    param([Parameter(Mandatory)][string]$Path)
    return ((Get-Content -Path $Path -Raw -Encoding utf8) -replace "`r`n", "`n").TrimEnd()
}

$parts = [System.Collections.Generic.List[string]]::new()

$parts.Add(@"
<#
.SYNOPSIS
    Every privileged Azure RBAC and Entra ID role assignment in your tenant, scored, in one HTML report.

.DESCRIPTION
    One file, nothing to install. Sign in, read, get a report you can hand to someone.

    Finds what the portal and posture tools do not put in one place: custom roles rated by the actions
    they really grant after NotActions, privilege inherited through nested groups with every member
    named, app registrations holding privileged roles with no valid credential, disabled users with
    permanent assignments, and PIM eligible and activated assignments next to permanent ones.

    Read-only. It signs in with read scopes, reads, and writes an HTML file. It changes nothing.

    To act on the findings rather than just read them, use the module. It returns the findings as
    objects and can remove an assignment with a prompt, a JSON backup and a refusal for anything
    inherited through a group, held in PIM, named as break-glass or belonging to you:

        Install-Module RiskyRolesAnalyzer -AllowPrerelease
        https://github.com/simon-vedder/risky-roles-analyzer

.PARAMETER OutputPath
    Where to write the report. Default: ./RiskyRolesAnalyzer-report-<timestamp>.html

.PARAMETER TenantId
    Tenant to sign in to. Without it the sign-in picks your home tenant.

.PARAMETER SubscriptionId
    Limit the Azure part to these subscriptions. Without it, every enabled subscription in the tenant.

.PARAMETER AdditionalAzureRole
    Azure role names to treat as privileged on top of the built-in list.

.PARAMETER AdditionalEntraRole
    Entra role names to treat as privileged on top of the built-in list.

.PARAMETER BreakGlassAccount
    UPNs or object ids of emergency access accounts. They are still reported, and marked so nobody
    acts on them by mistake.

.PARAMETER MinimumSeverity
    Drop findings below this severity. Default Info, which keeps everything.

.PARAMETER SkipAzure
    Entra ID only. No Azure sign-in, no Azure RBAC.

.PARAMETER SkipEntra
    Azure RBAC only.

.PARAMETER SkipPim
    Do not read PIM eligibility. Use it on tenants without Entra ID P2 to silence the warning.

.PARAMETER UseDeviceCode
    Device code sign-in, for hosts without a browser.

.PARAMETER NoOpen
    Do not open the report when it is written.

.EXAMPLE
    ./Invoke-RiskyRolesAudit.ps1

.EXAMPLE
    ./Invoke-RiskyRolesAudit.ps1 -BreakGlassAccount 'breakglass@contoso.com' -MinimumSeverity High

.EXAMPLE
    ./Invoke-RiskyRolesAudit.ps1 -SkipAzure -SkipPim -OutputPath ./entra.html

.NOTES
    Generated from the RiskyRolesAnalyzer module $version by tools/Build-StandaloneScript.ps1.
    Do not edit this file: change the module and rebuild, or the next build overwrites you.

    Requires PowerShell 7.2+ and the modules Az.Accounts, Az.Resources and
    Microsoft.Graph.Authentication. Install them once with:

        Install-Module Az.Accounts, Az.Resources, Microsoft.Graph.Authentication -Scope CurrentUser

    Required permissions: Azure Reader on the subscriptions you audit; Graph delegated scopes
    RoleManagement.Read.Directory, Directory.Read.All, Group.Read.All and Application.Read.All,
    which you consent to at sign-in. Entra ID P2 for the PIM parts.

    MIT licensed. https://github.com/simon-vedder/risky-roles-analyzer
#>
[CmdletBinding()]
param(
    [Parameter()]
    [string]`$OutputPath,

    [Parameter()]
    [string]`$TenantId,

    [Parameter()]
    [string[]]`$SubscriptionId,

    [Parameter()]
    [string[]]`$AdditionalAzureRole,

    [Parameter()]
    [string[]]`$AdditionalEntraRole,

    [Parameter()]
    [string[]]`$BreakGlassAccount,

    [Parameter()]
    [ValidateSet('Info', 'Low', 'Medium', 'High', 'Critical')]
    [string]`$MinimumSeverity = 'Info',

    [Parameter()]
    [switch]`$SkipAzure,

    [Parameter()]
    [switch]`$SkipEntra,

    [Parameter()]
    [switch]`$SkipPim,

    [Parameter()]
    [switch]`$UseDeviceCode,

    [Parameter()]
    [switch]`$NoOpen
)

Set-StrictMode -Version Latest
`$ErrorActionPreference = 'Stop'

# ================================================================================================
#  Generated file. Everything below comes from the module sources; edit those, then rebuild with
#  tools/Build-StandaloneScript.ps1. The module is the tested version: 144 Pester tests run against
#  a synthetic tenant, and the rules here are the same functions.
# ================================================================================================

`$script:ModuleVersion = '$version'
`$script:TypeName = @{
    Finding = 'RiskyRolesAnalyzer.RiskyRoleAssignment'
    Removal = 'RiskyRolesAnalyzer.RiskyRoleAssignmentRemoval'
    Restore = 'RiskyRolesAnalyzer.RiskyRoleAssignmentRestore'
}
"@)

# ---- the catalog, inlined ------------------------------------------------------------------------
$catalog = ((Get-Content -Path (Join-Path $moduleRoot 'RiskyRoleCatalog.psd1') -Raw -Encoding utf8) -replace "`r`n", "`n").TrimEnd()
$parts.Add(@"

# ---- Role lists, risky actions and scoring weights (RiskyRoleCatalog.psd1) ----------------------
`$script:Catalog = $catalog
"@)

# ---- the report template, inlined ----------------------------------------------------------------
# A here-string cannot contain its own terminator; the template has none, and this asserts it.
$template = ((Get-Content -Path (Join-Path $moduleRoot 'Resources' 'report.html') -Raw -Encoding utf8) -replace "`r`n", "`n")
if ($template -match "(?m)^'@") { throw "The report template contains a here-string terminator and cannot be inlined." }
$parts.Add(@"

# ---- The HTML report template (Resources/report.html) -------------------------------------------
`$script:ReportTemplate = @'
$($template.TrimEnd())
'@
"@)

# ---- functions -----------------------------------------------------------------------------------
# Dot-sourced files define functions before use at runtime, so file order does not matter for
# correctness; alphabetical keeps the diff stable.
$parts.Add("`n# ---- Rules and collectors (src/RiskyRolesAnalyzer/Private) --------------------------------------")
foreach ($file in @(Get-ChildItem -Path (Join-Path $moduleRoot 'Private') -Filter '*.ps1' | Sort-Object Name)) {
    # The disk-reading template lookup is replaced further down by one that returns the inlined copy.
    if ($file.BaseName -eq 'Get-RiskyRoleReportTemplate') { continue }
    $parts.Add("`n" + (Get-FunctionBody -Path $file.FullName))
}

$parts.Add("`n# ---- Commands (src/RiskyRolesAnalyzer/Public) ---------------------------------------------------")
foreach ($name in $publicNeeded) {
    $path = Join-Path $moduleRoot 'Public' "$name.ps1"
    if (-not (Test-Path -Path $path)) { throw "Missing $path" }
    $parts.Add("`n" + (Get-FunctionBody -Path $path))
}

# In the module this function reads the file; here the template is already in memory.
$parts.Add(@'

# ---- Get-RiskyRoleReportTemplate, the single-file variant ---------------------------------------
function Get-RiskyRoleReportTemplate {
    [CmdletBinding()]
    [OutputType([string])]
    param()

    return $script:ReportTemplate
}
'@)

# ---- main ----------------------------------------------------------------------------------------
$parts.Add(@'

# ================================================================================================
#  Main
# ================================================================================================

$connect = @{}
if ($TenantId) { $connect.TenantId = $TenantId }
if ($SkipAzure) { $connect.SkipAzure = $true }
if ($UseDeviceCode) { $connect.UseDeviceCode = $true }
$session = Connect-RiskyRolesAnalyzer @connect

Write-Host "Tenant $($session.TenantId)" -ForegroundColor Cyan
Write-Host "  Graph $($session.GraphAccount)" -ForegroundColor DarkGray
if ($session.AzureAccount) { Write-Host "  Azure $($session.AzureAccount)" -ForegroundColor DarkGray }

$audit = @{ MinimumSeverity = $MinimumSeverity }
foreach ($name in 'SubscriptionId', 'AdditionalAzureRole', 'AdditionalEntraRole', 'BreakGlassAccount') {
    if ($PSBoundParameters.ContainsKey($name)) { $audit[$name] = $PSBoundParameters[$name] }
}
foreach ($name in 'SkipAzure', 'SkipEntra', 'SkipPim') {
    if ($PSBoundParameters.ContainsKey($name)) { $audit[$name] = $PSBoundParameters[$name] }
}

$stopwatch = [System.Diagnostics.Stopwatch]::StartNew()
$findings = @(Get-RiskyRoleAssignment @audit)
$stopwatch.Stop()

if (-not $OutputPath) {
    $OutputPath = Join-Path (Get-Location) ('RiskyRolesAnalyzer-report-{0:yyyyMMdd-HHmmss}.html' -f (Get-Date))
}
$report = @{ Path = $OutputPath; TenantId = $session.TenantId; Confirm = $false }
if (-not $NoOpen) { $report.Open = $true }
$file = $findings | Export-RiskyRoleReport @report

Write-Host ''
Write-Host ("{0} finding(s) in {1} s" -f $findings.Count, [int]$stopwatch.Elapsed.TotalSeconds) -ForegroundColor Cyan
foreach ($group in ($findings | Group-Object Severity | Sort-Object { @{ Critical = 0; High = 1; Medium = 2; Low = 3; Info = 4 }[$_.Name] })) {
    $colour = switch ($group.Name) { 'Critical' { 'Red' } 'High' { 'Yellow' } default { 'DarkGray' } }
    Write-Host ("  {0,-9}{1}" -f $group.Name, $group.Count) -ForegroundColor $colour
}
Write-Host ''
Write-Host "Report: $($file.FullName)" -ForegroundColor Green
Write-Host 'To act on these findings instead of reading them, the module removes them with a prompt and a backup:' -ForegroundColor DarkGray
Write-Host '  Install-Module RiskyRolesAnalyzer -AllowPrerelease' -ForegroundColor DarkGray
'@)

$built = (($parts -join "`n") -replace "`r`n", "`n").TrimEnd() + "`n"

if ($Check) {
    if (-not (Test-Path -Path $outputPath)) { throw "Missing dist/Invoke-RiskyRolesAudit.ps1. Run ./tools/Build-StandaloneScript.ps1 and commit it." }
    $current = ((Get-Content -Path $outputPath -Raw -Encoding utf8) -replace "`r`n", "`n")
    if ($current -ne $built) { throw "dist/Invoke-RiskyRolesAudit.ps1 is out of date. Run ./tools/Build-StandaloneScript.ps1 and commit the result." }
    "The standalone script matches the module sources."
    return
}

$null = New-Item -ItemType Directory -Path (Split-Path -Path $outputPath -Parent) -Force
Set-Content -Path $outputPath -Value $built -Encoding utf8 -NoNewline

$errors = $null
$null = [System.Management.Automation.Language.Parser]::ParseFile($outputPath, [ref]$null, [ref]$errors)
if (@($errors).Count) {
    @($errors) | ForEach-Object { Write-Warning "line $($_.Extent.StartLineNumber): $($_.Message)" }
    throw "The generated script does not parse."
}

$lineCount = @(Get-Content -Path $outputPath).Count
$sizeKb = [int]((Get-Item -Path $outputPath).Length / 1kb)
"Wrote dist/Invoke-RiskyRolesAudit.ps1 ($lineCount lines, $sizeKb KB) from module $version."
